# eureka:
#     client:
#         fetch-registry: true
#         register-with-eureka: true
#         serviceUrl:
#             defaultZone: http://localhost:8761/eureka/
#     instance:
#         prefer-ip-address: true
server:
    port: 9000
spring:
    application:
        name: ApiGateway-Service
        #this configguration property is middle level 
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/jit9628/microservices-configuration-server.git
        gateway:
            routes:
            - id: PRODUCT
              uri: lb://PRODUCT
              predicates:
              - Path: /api/product/**
            
